version: '3'

services:
  web:
    image: mrezabarkhordari/php-pgsql
    container_name: php-web
    restart: always
    networks:
      - web-backend

  database:
    image: postgres:12
    container_name: postgres-db
    restart: always
    environment:
      POSTGRESS_USER: db_user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: db_name
    networks:
      - web-backend
    volumes:
      - type: volume
        source: postgres-vol
        target: /var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - web-backend


networks:
  web-backend:

volumes:
  postgres-vol:
