apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: develop
  labels:
    app: php
    kind: deployment
spec:
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: php:7.4-apache
        envFrom:
        - configMapRef:
            name: php-configmap
        - secretRef:
            name: postgres-secret
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php
  namespace: develop
  labels:
    type: service
spec:
  type: ClusterIP
  selector:
    app: php
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-configmap
  namespace: develop
  labels:
    kind: configmap
data:
  POSTGRES_DB: php-db
  REDIS_HOST: redis
  REDIS_PORT: 6379
